### ISSUE TITLE
Add support for iterators

### ISSUE THREAD

**Issue by dondish** [auguwu/immutable#184]
All collection types should have some kind of support for iterators, if they are iterable, so they can be used in a for-each loop.

**Comment by auguwu** [comment]
Collection is an extension of `Map` and `Map`s are iterable by default
Pair -- I don't see a point of iterating it
Queue -- Already implemented
TimedQueue -- Don't see a point of adding it, like with Pair

**Comment by dondish** [comment]
Didn't see it implementing it, my bad
